version: '3'

networks:
  docker_net:
    external: true

services:
  reverse-proxy:
    build: .
    image: registry.gitlab.com/iceoid/docker-nginx-rproxy:latest
    container_name: reverse_proxy
    hostname: reverse_proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - docker_net
    volumes:
      - ${PWD}/certs/:/etc/ssl/private/
      - ${PWD}/conf.d/:/etc/nginx/conf.d/
      - ${PWD}/sites-available/:/etc/nginx/sites-available/
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
